var solitairenBaseUrl='https://solitairen.com/'
function clearUselessStorage(){Object.keys(localStorage).forEach(key=>{if(key.toString().includes('solitairen')&&!key.toString().includes("gameWinCount")){localStorage.removeItem(key);}});}
function hideIt(){$('#nomoremove-dialog-solitairen').attr("hidden",true);}
function hideItWin(){$('#win-dialog-solitairen').attr("hidden",true);}
function intializeFoundations(count,endCount,goDown){onresize=(event)=>{setTimeout(()=>setFoundations(true),10);setTimeout(()=>setFoundations(true),200);setTimeout(()=>setFoundations(true),1500);};setTimeout(()=>setFoundations(false),250);setTimeout(()=>setFoundations(false),500);setTimeout(()=>setFoundations(false),1000);setTimeout(()=>setFoundations(false),1500);setTimeout(()=>setFoundations(false),2000);function setFoundations(set,val){if($('[id^=dynamic]').length==count){if(!set){return;}}
for(let i=0;i<count;i++){$('#dynamic').remove();}
var counter=1;if(endCount==1){counter=2;}
$(".foundation").each(function(){var result=$(this).css('translate').split(',');var width=$(this).css('width');var height=$(this).css('height');var img=$('<img id="dynamic">');img.attr('src','rideordie/solitaire/images/spots/146x198/foundation_spot'+counter+'.webp');img.attr('alt','suit-image');img.attr('style','position: absolute; height: '+height+'; width: '+width+'; border - radius: 4px; transform: translate3d('+result[0]+','+result[1]+', 0px) scaleZ(1);');img.appendTo('#playArea');if(endCount!=1){if(goDown){counter--;if(counter<1){counter=endCount;}}else{counter++;if(counter>endCount){counter=1;}}}});}}
function changeWindow(){var el=document.getElementById('gogo');var value=$('#screenSize').attr('val');if(value=='1'){$('#screenSize').attr('val',2);toggleFullScreen(el);}
else{$('#screenSize').attr('val',1);toggleFullScreen();}
function toggleFullScreen(elem){if((document.fullScreenElement!==undefined&&document.fullScreenElement===null)||(document.msFullscreenElement!==undefined&&document.msFullscreenElement===null)||(document.mozFullScreen!==undefined&&!document.mozFullScreen)||(document.webkitIsFullScreen!==undefined&&!document.webkitIsFullScreen)){if(elem.requestFullScreen){elem.requestFullScreen();}else if(elem.mozRequestFullScreen){elem.mozRequestFullScreen();}else if(elem.webkitRequestFullScreen){elem.webkitRequestFullScreen(Element.ALLOW_KEYBOARD_INPUT);}else if(elem.msRequestFullscreen){elem.msRequestFullscreen();}}else{if(document.cancelFullScreen){document.cancelFullScreen();}else if(document.mozCancelFullScreen){document.mozCancelFullScreen();}else if(document.webkitCancelFullScreen){document.webkitCancelFullScreen();}else if(document.msExitFullscreen){document.msExitFullscreen();}}}}
function showDropdown(){document.getElementById("myDropdown").classList.toggle("show-sol");}
window.onclick=function(event){if(!event.target.matches('.dropbtn-sol')){var dropdowns=document.getElementsByClassName("dropdown-content-sol");var i;for(i=0;i<dropdowns.length;i++){var openDropdown=dropdowns[i];if(openDropdown.classList.contains('show-sol')){openDropdown.classList.remove('show-sol');}}}
if(!event.target.matches('#all-games')){$('.dropdown-content-all').css('display','none');}}
function setNewBackCard(type){window.onbeforeunload=null;sendEventGtag('new_cardback');localStorage.setItem('backCardNew',type);var modal=document.getElementById("backCardsModal");modal.style.display="none";location.reload();}
function setNewFaceCard(type){window.onbeforeunload=null;sendEventGtag('new_facecard');localStorage.setItem('faceCard',type);var modal=document.getElementById("faceCardsModal");modal.style.display="none";location.reload();}
function showModal(id){var modal=document.getElementById(id);modal.style.display="block";}
function closeModal(id){var modal=document.getElementById(id);modal.style.display="none";}
function setCookie(cname,cvalue,exdays){const d=new Date();d.setTime(d.getTime()+(exdays*24*60*60*1000));let expires="expires="+d.toUTCString();document.cookie=cname+"="+cvalue+";"+expires+";path=/";}
var value=localStorage.getItem('color');if(value==null||value==undefined){$("#game-ui").css("background-color",'#076D2B');$("#wrapper").css("background-color",'#076D2B');$("#parent-game").css("background-color",'#076D2B');$('.clr-field').css('color','#076D2B');$('#colorVal').val='#076D2B';setCookie('color','#076D2B',365);}else{$("#game-ui").css("background-color",value);$("#wrapper").css("background-color",value);$("#parent-game").css("background-color",value);$('.clr-field').css('color',value);$('#colorVal').val=value;setCookie('color',value,365);}
$(window).on("load",function(){var value=localStorage.getItem('color');if(value==null||value==undefined){$('.clr-field').css('color','#076D2B');$('#colorVal').attr('value','#076D2B');}else{$('.clr-field').css('color',value);$('#colorVal').attr('value',value);}});Coloris({el:'.coloris',swatches:['#264653','#2a9d8f','#e9c46a','#f4a261','#e76f51','#d62828','#023e8a','#0077b6','#0096c7','#00b4d8','#48cae4'],onChange:(color)=>{$("#game-ui").css("background-color",color);$("#wrapper").css("background-color",color);$("#parent-game").css("background-color",color);localStorage.setItem('color',color);},defaultColor:'#076D2B',});Coloris.setInstance('.instance1',{theme:'pill',themeMode:'dark',formatToggle:true,closeButton:true,clearButton:true,swatches:['#067bc2','#84bcda','#80e377','#ecc30b','#f37748','#d56062']});function isMobile(){var t=navigator.userAgent.toLowerCase();return t.match(/Mobile|Windows Phone|Lumia|Android|webOS|iPhone|iPod|Blackberry|PlayBook|BB10|Opera Mini|\bCrMo\/|Opera Mobi/i)?"phone":null;}
function sendEventGtag(value){try{if(isMobile()){track({type:value});}else{gtag('event',value);}}catch(e){}}
function addJsFile(path){var jsGame=document.createElement('script');jsGame.src=path;var sc=document.getElementsByTagName('script')[0];sc.parentNode.insertBefore(jsGame,sc);}